2022/07/01 06:28:08 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "homde/index". in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('homde/index')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=homde/index
---
2022/07/01 06:45:22 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "hello". in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php:486
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(270): CController->missingAction('hello')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): CController->run('hello')
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('site/hello')
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php?r=site/hello
---
2022/07/01 06:47:00 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "favicon.ico". in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://yii.com/site/helloworld
---
2022/07/01 06:57:19 [error] [php] Trying to access array offset on value of type int (E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\views\home\index.php:4)
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CBaseController.php(126): require()
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CBaseController.php(95): HomeController->renderInternal()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(872): HomeController->renderFile()
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(785): HomeController->renderPartial()
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php(15): HomeController->render()
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\actions\CInlineAction.php(49): HomeController->actionIndex()
#6 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams()
#7 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(286): HomeController->runAction()
#8 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(265): HomeController->runActionWithFilters()
#9 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): HomeController->run()
#10 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController()
#11 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#12 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(13): CWebApplication->run()
REQUEST_URI=/home/index
in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\views\home\index.php (4)
in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php (15)
in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php (13)
2022/07/01 06:57:49 [error] [php] Trying to access array offset on value of type int (E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\views\home\index.php:7)
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CBaseController.php(126): require()
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CBaseController.php(95): HomeController->renderInternal()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(872): HomeController->renderFile()
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(785): HomeController->renderPartial()
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php(15): HomeController->render()
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\actions\CInlineAction.php(49): HomeController->actionIndex()
#6 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams()
#7 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(286): HomeController->runAction()
#8 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(265): HomeController->runActionWithFilters()
#9 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): HomeController->run()
#10 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController()
#11 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#12 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(13): CWebApplication->run()
REQUEST_URI=/home/index
in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\views\home\index.php (7)
in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php (15)
in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php (13)
2022/07/01 07:00:11 [error] [php] Array to string conversion (E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\views\home\index.php:4)
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CBaseController.php(126): require()
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CBaseController.php(95): HomeController->renderInternal()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(872): HomeController->renderFile()
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(785): HomeController->renderPartial()
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php(18): HomeController->render()
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\actions\CInlineAction.php(49): HomeController->actionIndex()
#6 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams()
#7 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(286): HomeController->runAction()
#8 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(265): HomeController->runActionWithFilters()
#9 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): HomeController->run()
#10 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController()
#11 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#12 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(13): CWebApplication->run()
REQUEST_URI=/home/index
in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\views\home\index.php (4)
in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php (18)
in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php (13)
2022/07/01 08:17:50 [error] [exception.CDbException] CDbException: CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'testdrive' in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\db\CDbConnection.php:399
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CModule.php(394): CDbConnection->init()
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CModule.php(103): CModule->getComponent('db')
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\gii\generators\crud\CrudCode.php(44): CModule->__get('db')
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CFormModel.php(39): CrudCode->init()
#6 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): CController->run('index')
#13 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/crud/index')
#14 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php/gii/crud/index
HTTP_REFERER=http://yii.com/index.php/gii/default/index
---
2022/07/01 08:42:00 [error] [php] Undefined index: ajax (E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\SiteController.php:87)
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(286): SiteController->runAction()
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(265): SiteController->runActionWithFilters()
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): SiteController->run()
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController()
#6 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#7 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php/site/login
in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\SiteController.php (87)
in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php (13)
2022/07/01 08:44:48 [error] [php] Undefined index: LoginForm (E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\SiteController.php:93)
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(286): SiteController->runAction()
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(265): SiteController->runActionWithFilters()
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): SiteController->run()
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController()
#6 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#7 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php/site/login
in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\SiteController.php (93)
in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php (13)
2022/07/01 08:56:59 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "favicon.ico". in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://yii.com/index.php/event/admin
---
2022/07/01 08:57:12 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "favicon.ico". in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://yii.com/index.php/event/admin
---
2022/07/01 09:13:07 [error] [exception.CHttpException.403] CHttpException: You are not authorized to perform this action. in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\auth\CAccessControlFilter.php:183
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(291): CFilterChain->run()
#6 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): CController->run('event')
#8 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('event/event')
#9 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/event/event
---
2022/07/01 09:13:26 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "event_find". in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php:486
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(270): CController->missingAction('event_find')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): CController->run('event_find')
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('event/event_fin...')
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/event/event_find
---
2022/07/01 09:13:50 [error] [exception.CHttpException.403] CHttpException: You are not authorized to perform this action. in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\auth\CAccessControlFilter.php:183
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(291): CFilterChain->run()
#6 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): CController->run('events')
#8 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('event/events')
#9 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/event/events
---
2022/07/01 09:13:58 [error] [exception.CHttpException.403] CHttpException: You are not authorized to perform this action. in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\auth\CAccessControlFilter.php:183
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(291): CFilterChain->run()
#6 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): CController->run('events')
#8 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('event/events')
#9 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/event/events
---
2022/07/01 09:14:18 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "loadmodel". in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php:486
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(270): CController->missingAction('loadmodel')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): CController->run('loadmodel')
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('event/loadmodel')
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/event/loadmodel
---
2022/07/01 09:14:42 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "loadmodel". in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php:486
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(270): CController->missingAction('loadmodel')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): CController->run('loadmodel')
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('event/loadmodel')
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/event/loadmodel
---
2022/07/01 09:23:19 [error] [exception.CException] CException: Alias "app.models.Event" is invalid. Make sure it points to an existing directory or file. in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\YiiBase.php:355
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\gii\generators\crud\CrudCode.php(59): YiiBase::import('app.models.Even...', true)
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\validators\CInlineValidator.php(42): CrudCode->validateModel('model', Array)
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(CrudCode), 'model')
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CModel.php(159): CValidator->validate(Object(CrudCode), Array)
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\gii\CCodeGenerator.php(159): CModel->validate()
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#6 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#7 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): CController->run('index')
#11 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/crud/index')
#12 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/index.php/gii/crud/index
HTTP_REFERER=http://yii.com/index.php/gii/crud/index
---
2022/07/01 10:28:38 [error] [exception.CException] CException: Property "CStringValidator.0" is not defined. in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CComponent.php:173
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\validators\CValidator.php(177): CComponent->__set('0', 'required')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CModel.php(287): CValidator::createValidator(0, Object(Event), Array, Array)
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CModel.php(260): CModel->createValidators()
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CModel.php(304): CModel->getValidators('author')
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\helpers\CHtml.php(1534): CModel->isAttributeRequired('author')
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\widgets\CActiveForm.php(601): CHtml::activeLabelEx(Object(Event), 'author', Array)
#6 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\views\event\_form.php(23): CActiveForm->labelEx(Object(Event), 'author')
#7 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CBaseController.php(126): require('E:\\xampp\\htdocs...')
#8 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CBaseController.php(95): CBaseController->renderInternal('E:\\xampp\\htdocs...', Array, true)
#9 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(872): CBaseController->renderFile('E:\\xampp\\htdocs...', Array, true)
#10 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\views\event\create.php(18): CController->renderPartial('_form', Array)
#11 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CBaseController.php(126): require('E:\\xampp\\htdocs...')
#12 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CBaseController.php(95): CBaseController->renderInternal('E:\\xampp\\htdocs...', Array, true)
#13 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(872): CBaseController->renderFile('E:\\xampp\\htdocs...', Array, true)
#14 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(785): CController->renderPartial('create', Array, true)
#15 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\EventController.php(78): CController->render('create', Array)
#16 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\actions\CInlineAction.php(49): EventController->actionCreate()
#17 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#18 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#19 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\filters\CFilter.php(40): CFilterChain->run()
#20 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#21 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#22 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#23 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(291): CFilterChain->run()
#24 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#25 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): CController->run('create')
#26 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('event/create')
#27 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#28 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(13): CApplication->run()
#29 {main}
REQUEST_URI=/index.php/event/create
HTTP_REFERER=http://yii.com/index.php/event/4
---
2022/07/01 10:28:42 [error] [exception.CException] CException: Property "CStringValidator.0" is not defined. in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CComponent.php:173
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\validators\CValidator.php(177): CComponent->__set('0', 'required')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CModel.php(287): CValidator::createValidator(0, Object(Event), Array, Array)
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CModel.php(260): CModel->createValidators()
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CModel.php(304): CModel->getValidators('author')
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\helpers\CHtml.php(1534): CModel->isAttributeRequired('author')
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\widgets\CActiveForm.php(601): CHtml::activeLabelEx(Object(Event), 'author', Array)
#6 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\views\event\_form.php(23): CActiveForm->labelEx(Object(Event), 'author')
#7 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CBaseController.php(126): require('E:\\xampp\\htdocs...')
#8 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CBaseController.php(95): CBaseController->renderInternal('E:\\xampp\\htdocs...', Array, true)
#9 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(872): CBaseController->renderFile('E:\\xampp\\htdocs...', Array, true)
#10 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\views\event\create.php(18): CController->renderPartial('_form', Array)
#11 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CBaseController.php(126): require('E:\\xampp\\htdocs...')
#12 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CBaseController.php(95): CBaseController->renderInternal('E:\\xampp\\htdocs...', Array, true)
#13 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(872): CBaseController->renderFile('E:\\xampp\\htdocs...', Array, true)
#14 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(785): CController->renderPartial('create', Array, true)
#15 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\EventController.php(78): CController->render('create', Array)
#16 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\actions\CInlineAction.php(49): EventController->actionCreate()
#17 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#18 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#19 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\filters\CFilter.php(40): CFilterChain->run()
#20 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#21 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#22 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#23 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(291): CFilterChain->run()
#24 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#25 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): CController->run('create')
#26 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('event/create')
#27 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#28 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(13): CApplication->run()
#29 {main}
REQUEST_URI=/index.php/event/create
---
2022/07/01 11:28:13 [error] [exception.Error] Error: Object of class LoginForm could not be converted to string in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\helpers\CHtml.php:2408
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\helpers\CHtml.php(2408): str_replace(Array, Array, Object(LoginForm))
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\helpers\CHtml.php(1467): CHtml::getIdByName(Object(LoginForm))
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\helpers\CHtml.php(857): CHtml::inputField('password', Object(LoginForm), 'password', Array)
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\views\site\login.php(35): CHtml::passwordField(Object(LoginForm), 'password')
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CBaseController.php(126): require('E:\\xampp\\htdocs...')
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CBaseController.php(95): CBaseController->renderInternal('E:\\xampp\\htdocs...', Array, true)
#6 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(872): CBaseController->renderFile('E:\\xampp\\htdocs...', Array, true)
#7 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(785): CController->renderPartial('login', Array, true)
#8 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\SiteController.php(102): CController->render('login', Array)
#9 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#10 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): CController->run('login')
#14 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#15 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#16 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/index.php/site/login
---
2022/07/01 12:27:39 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "favicon.ico". in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://yii.com/
---
2022/07/01 12:27:39 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "favicon.ico". in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://yii.com/
---
2022/07/01 12:27:39 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "favicon.ico". in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://yii.com/
---
2022/07/04 04:15:53 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "favicon.ico". in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://yii.com/
---
2022/07/04 04:16:59 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "analytics/default/index". in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('analytics/defau...')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/
---
2022/07/04 04:16:59 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "favicon.ico". in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://yii-home.com/
---
2022/07/04 04:28:18 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "favicon.ico". in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://yii-event.com/
---
2022/07/04 04:29:00 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "favicon.ico". in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://yii-home.com/
---
2022/07/04 04:52:11 [error] [exception.CException] CException: Property "HomeController.domain" is not defined. in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CComponent.php:173
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php(13): CComponent->__set('domain', 'yii-home.com')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(359): HomeController->__construct('home', NULL)
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(276): CWebApplication->createController('index/')
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('home/index')
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(14): CApplication->run()
#6 {main}
REQUEST_URI=/
---
2022/07/04 04:52:35 [error] [exception.Error] Error: Call to undefined function dđ() in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php:17
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\actions\CInlineAction.php(49): HomeController->actionIndex()
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): CController->run('index')
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('home/index')
#6 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#7 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(14): CApplication->run()
#8 {main}
REQUEST_URI=/
---
2022/07/04 04:52:36 [error] [exception.Error] Error: Call to undefined function dđ() in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php:17
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\actions\CInlineAction.php(49): HomeController->actionIndex()
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): CController->run('index')
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('home/index')
#6 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#7 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(14): CApplication->run()
#8 {main}
REQUEST_URI=/
---
2022/07/04 04:52:36 [error] [exception.Error] Error: Call to undefined function dđ() in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php:17
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\actions\CInlineAction.php(49): HomeController->actionIndex()
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): CController->run('index')
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('home/index')
#6 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#7 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(14): CApplication->run()
#8 {main}
REQUEST_URI=/
---
2022/07/04 05:19:59 [error] [exception.CException] CException: CUrlManager.UrlFormat must be either "path" or "get". in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CUrlManager.php:514
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CComponent.php(152): CUrlManager->setUrlFormat('thanhran')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\YiiBase.php(227): CComponent->__set('urlFormat', 'thanhran')
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(531): CModule->getComponent('urlManager')
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(140): CApplication->getUrlManager()
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#6 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(36): CApplication->run()
#7 {main}
REQUEST_URI=/
---
2022/07/04 05:23:01 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "en". in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('en')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(36): CApplication->run()
#3 {main}
REQUEST_URI=/en
---
2022/07/04 05:56:35 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "favicon.ico". in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(36): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://yii-home.com/site/page/view/about/
---
2022/07/04 05:56:35 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "favicon.ico". in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(36): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://yii-home.com/site/page/view/about/
---
2022/07/04 05:57:41 [error] [php] Undefined offset: 0 (E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\zii\widgets\CMenu.php:314)
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\zii\widgets\CMenu.php(293): CMenu->isItemActive()
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\zii\widgets\CMenu.php(161): CMenu->normalizeItems()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CBaseController.php(147): CMenu->init()
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CBaseController.php(181): SiteController->createWidget()
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\views\layouts\main.php(36): SiteController->widget()
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CBaseController.php(126): require()
#6 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CBaseController.php(95): SiteController->renderInternal()
#7 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\widgets\CContentDecorator.php(76): SiteController->renderFile()
#8 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate()
#9 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput()
#10 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CBaseController.php(215): CContentDecorator->run()
#11 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CBaseController.php(309): SiteController->endWidget()
#12 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\views\layouts\column1.php(6): SiteController->endContent()
#13 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CBaseController.php(126): require()
#14 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CBaseController.php(95): SiteController->renderInternal()
#15 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(787): SiteController->renderFile()
#16 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\actions\CViewAction.php(140): SiteController->render()
#17 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\actions\CAction.php(76): CViewAction->run()
#18 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(308): CViewAction->runWithParams()
#19 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(286): SiteController->runAction()
#20 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(265): SiteController->runActionWithFilters()
#21 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): SiteController->run()
#22 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController()
#23 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#24 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(36): CWebApplication->run()
REQUEST_URI=/site/page/view/about/
in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\views\layouts\main.php (36)
in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\views\layouts\column1.php (6)
in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php (36)
2022/07/04 05:58:00 [error] [exception.ParseError] ParseError: syntax error, unexpected ';', expecting ')' in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\views\layouts\main.php:38
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CBaseController.php(95): CBaseController->renderInternal('E:\\xampp\\htdocs...', Array, true)
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('E:\\xampp\\htdocs...', Array, true)
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CBaseController.php(215): COutputProcessor->run()
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CBaseController.php(309): CBaseController->endWidget('CContentDecorat...')
#6 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\views\layouts\column1.php(6): CBaseController->endContent()
#7 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CBaseController.php(126): require('E:\\xampp\\htdocs...')
#8 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CBaseController.php(95): CBaseController->renderInternal('E:\\xampp\\htdocs...', Array, true)
#9 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(787): CBaseController->renderFile('E:\\xampp\\htdocs...', Array, true)
#10 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\actions\CViewAction.php(140): CController->render('pages/about')
#11 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\actions\CAction.php(76): CViewAction->run()
#12 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(308): CAction->runWithParams(Array)
#13 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(286): CController->runAction(Object(CViewAction))
#14 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#15 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): CController->run('page')
#16 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('site/page/view/...')
#17 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#18 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(36): CApplication->run()
#19 {main}
REQUEST_URI=/site/page/view/about/
HTTP_REFERER=http://yii-home.com/site/index/
---
2022/07/04 05:58:01 [error] [exception.ParseError] ParseError: syntax error, unexpected ';', expecting ')' in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\views\layouts\main.php:38
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CBaseController.php(95): CBaseController->renderInternal('E:\\xampp\\htdocs...', Array, true)
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('E:\\xampp\\htdocs...', Array, true)
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CBaseController.php(215): COutputProcessor->run()
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CBaseController.php(309): CBaseController->endWidget('CContentDecorat...')
#6 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\views\layouts\column1.php(6): CBaseController->endContent()
#7 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CBaseController.php(126): require('E:\\xampp\\htdocs...')
#8 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CBaseController.php(95): CBaseController->renderInternal('E:\\xampp\\htdocs...', Array, true)
#9 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(787): CBaseController->renderFile('E:\\xampp\\htdocs...', Array, true)
#10 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\actions\CViewAction.php(140): CController->render('pages/about')
#11 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\actions\CAction.php(76): CViewAction->run()
#12 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(308): CAction->runWithParams(Array)
#13 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(286): CController->runAction(Object(CViewAction))
#14 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#15 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): CController->run('page')
#16 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('site/page/view/...')
#17 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#18 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(36): CApplication->run()
#19 {main}
REQUEST_URI=/site/page/view/about/
HTTP_REFERER=http://yii-home.com/site/index/
---
2022/07/04 05:58:53 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "favicon.ico". in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(36): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://yii-event.com/event/index
---
2022/07/04 05:59:44 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "favicon.ico". in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(36): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://yii-site.com/site
---
2022/07/04 06:05:33 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "favicon.ico". in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://yii-home.com/home
---
2022/07/04 06:05:33 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "favicon.ico". in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://yii-home.com/home
---
2022/07/04 06:05:33 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "favicon.ico". in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://yii-home.com/home
---
2022/07/04 06:05:34 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "favicon.ico". in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://yii-home.com/home
---
2022/07/04 06:06:18 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "favicon.ico". in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://yii-home.com/home
---
2022/07/04 06:06:19 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "favicon.ico". in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://yii-home.com/home
---
2022/07/04 06:06:19 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "favicon.ico". in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://yii-home.com/home
---
2022/07/04 06:06:19 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "favicon.ico". in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://yii-home.com/home
---
2022/07/04 06:06:20 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "favicon.ico". in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://yii-home.com/home
---
2022/07/04 06:06:20 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "favicon.ico". in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://yii-home.com/home
---
2022/07/04 06:14:17 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "favicon.ico". in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://yii-home.com/
---
2022/07/04 06:23:36 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "favicon.ico". in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://yii-event.com/
---
2022/07/04 06:30:56 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "favicon.ico". in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(14): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://yii-site.com/
---
2022/07/04 06:32:23 [error] [exception.CHttpException.404] CHttpException: Page not found in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php:25
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\actions\CInlineAction.php(49): HomeController->actionIndex()
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): CController->run('')
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('home')
#6 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#7 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(14): CApplication->run()
#8 {main}
REQUEST_URI=/home
---
2022/07/04 06:32:34 [error] [exception.CHttpException.404] CHttpException: Page not found in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php:25
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\actions\CInlineAction.php(49): HomeController->actionIndex()
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): CController->run('')
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('home')
#6 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#7 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(14): CApplication->run()
#8 {main}
REQUEST_URI=/home
---
2022/07/04 06:32:34 [error] [exception.CHttpException.404] CHttpException: Page not found in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php:25
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\actions\CInlineAction.php(49): HomeController->actionIndex()
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): CController->run('')
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('home')
#6 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#7 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(14): CApplication->run()
#8 {main}
REQUEST_URI=/home
---
2022/07/04 06:32:34 [error] [exception.CHttpException.404] CHttpException: Page not found in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php:25
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\actions\CInlineAction.php(49): HomeController->actionIndex()
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): CController->run('')
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('home')
#6 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#7 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(14): CApplication->run()
#8 {main}
REQUEST_URI=/home
---
2022/07/04 06:32:41 [error] [exception.CHttpException.404] CHttpException: Page not found in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php:25
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\actions\CInlineAction.php(49): HomeController->actionIndex()
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): CController->run('')
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('home')
#6 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#7 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(14): CApplication->run()
#8 {main}
REQUEST_URI=/home
---
2022/07/04 06:32:50 [error] [exception.CHttpException.404] CHttpException: Page not found in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php:25
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\actions\CInlineAction.php(49): HomeController->actionIndex()
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): CController->run('')
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('home')
#6 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#7 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(14): CApplication->run()
#8 {main}
REQUEST_URI=/home
---
2022/07/04 06:32:54 [error] [exception.CHttpException.404] CHttpException: Page not found in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php:25
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\actions\CInlineAction.php(49): HomeController->actionIndex()
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): CController->run('')
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('home')
#6 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#7 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(14): CApplication->run()
#8 {main}
REQUEST_URI=/home
---
2022/07/04 06:32:58 [error] [exception.CHttpException.404] CHttpException: Page not found in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php:25
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\actions\CInlineAction.php(49): HomeController->actionIndex()
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): CController->run('')
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('home')
#6 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#7 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(14): CApplication->run()
#8 {main}
REQUEST_URI=/home
---
2022/07/04 06:32:59 [error] [exception.CHttpException.404] CHttpException: Page not found in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php:25
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\actions\CInlineAction.php(49): HomeController->actionIndex()
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): CController->run('')
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('home')
#6 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#7 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(14): CApplication->run()
#8 {main}
REQUEST_URI=/home
---
2022/07/04 06:32:59 [error] [exception.CHttpException.404] CHttpException: Page not found in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php:25
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\actions\CInlineAction.php(49): HomeController->actionIndex()
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): CController->run('')
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('home')
#6 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#7 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(14): CApplication->run()
#8 {main}
REQUEST_URI=/home
---
2022/07/04 06:32:59 [error] [exception.CHttpException.404] CHttpException: Page not found in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php:25
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\actions\CInlineAction.php(49): HomeController->actionIndex()
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): CController->run('')
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('home')
#6 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#7 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(14): CApplication->run()
#8 {main}
REQUEST_URI=/home
---
2022/07/04 06:33:36 [error] [exception.CHttpException.404] CHttpException: Page not found in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php:30
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\actions\CInlineAction.php(49): HomeController->actionIndex()
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): CController->run('')
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('home')
#6 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#7 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(14): CApplication->run()
#8 {main}
REQUEST_URI=/home
---
2022/07/04 06:33:37 [error] [exception.CHttpException.404] CHttpException: Page not found in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php:30
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\actions\CInlineAction.php(49): HomeController->actionIndex()
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): CController->run('')
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('home')
#6 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#7 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(14): CApplication->run()
#8 {main}
REQUEST_URI=/home
---
2022/07/04 06:33:38 [error] [exception.CHttpException.404] CHttpException: Page not found in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php:30
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\actions\CInlineAction.php(49): HomeController->actionIndex()
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): CController->run('')
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('home')
#6 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#7 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(14): CApplication->run()
#8 {main}
REQUEST_URI=/home
---
2022/07/04 06:33:38 [error] [exception.CHttpException.404] CHttpException: Page not found in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php:30
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\actions\CInlineAction.php(49): HomeController->actionIndex()
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): CController->run('')
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('home')
#6 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#7 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(14): CApplication->run()
#8 {main}
REQUEST_URI=/home
---
2022/07/04 06:35:30 [error] [exception.CHttpException.404] CHttpException: Page not found in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php:19
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php(30): HomeController->checkDomain()
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\actions\CInlineAction.php(49): HomeController->actionIndex()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): CController->run('')
#6 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('home')
#7 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#8 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(14): CApplication->run()
#9 {main}
REQUEST_URI=/home
---
2022/07/04 06:35:31 [error] [exception.CHttpException.404] CHttpException: Page not found in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php:19
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php(30): HomeController->checkDomain()
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\actions\CInlineAction.php(49): HomeController->actionIndex()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): CController->run('')
#6 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('home')
#7 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#8 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(14): CApplication->run()
#9 {main}
REQUEST_URI=/home
---
2022/07/04 06:35:38 [error] [exception.CHttpException.404] CHttpException: Page not found in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php:19
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php(30): HomeController->checkDomain()
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\actions\CInlineAction.php(49): HomeController->actionIndex()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): CController->run('')
#6 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('home')
#7 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#8 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(14): CApplication->run()
#9 {main}
REQUEST_URI=/home
---
2022/07/04 06:35:49 [error] [exception.CHttpException.404] CHttpException: Page not found in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php:20
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php(31): HomeController->checkDomain()
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\actions\CInlineAction.php(49): HomeController->actionIndex()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): CController->run('')
#6 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('home')
#7 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#8 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(14): CApplication->run()
#9 {main}
REQUEST_URI=/home
---
2022/07/04 06:36:25 [error] [exception.CHttpException.404] CHttpException: Page not found in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php:19
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php(30): HomeController->checkDomain()
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\actions\CInlineAction.php(49): HomeController->actionIndex()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): CController->run('')
#6 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('home')
#7 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#8 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(14): CApplication->run()
#9 {main}
REQUEST_URI=/home
---
2022/07/04 06:36:26 [error] [exception.CHttpException.404] CHttpException: Page not found in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php:19
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php(30): HomeController->checkDomain()
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\actions\CInlineAction.php(49): HomeController->actionIndex()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): CController->run('')
#6 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('home')
#7 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#8 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(14): CApplication->run()
#9 {main}
REQUEST_URI=/home
---
2022/07/04 06:37:04 [error] [exception.CHttpException.404] CHttpException: Page not found in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php:20
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php(31): HomeController->checkDomain()
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\actions\CInlineAction.php(49): HomeController->actionIndex()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): CController->run('')
#6 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('home')
#7 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#8 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(14): CApplication->run()
#9 {main}
REQUEST_URI=/home
---
2022/07/04 06:39:47 [error] [php] Trying to get property 'action' of non-object (E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php:19)
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php(35): HomeController->checkDomain()
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\actions\CInlineAction.php(49): HomeController->actionIndex()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(286): HomeController->runAction()
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(265): HomeController->runActionWithFilters()
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): HomeController->run()
#6 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#8 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(14): CWebApplication->run()
REQUEST_URI=/home
in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php (19)
in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php (35)
in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php (14)
2022/07/04 06:39:48 [error] [php] Trying to get property 'action' of non-object (E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php:19)
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php(35): HomeController->checkDomain()
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\actions\CInlineAction.php(49): HomeController->actionIndex()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(286): HomeController->runAction()
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(265): HomeController->runActionWithFilters()
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): HomeController->run()
#6 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#8 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(14): CWebApplication->run()
REQUEST_URI=/home
in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php (19)
in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php (35)
in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php (14)
2022/07/04 06:39:48 [error] [php] Trying to get property 'action' of non-object (E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php:19)
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php(35): HomeController->checkDomain()
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\actions\CInlineAction.php(49): HomeController->actionIndex()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(286): HomeController->runAction()
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(265): HomeController->runActionWithFilters()
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): HomeController->run()
#6 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#8 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(14): CWebApplication->run()
REQUEST_URI=/home
in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php (19)
in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php (35)
in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php (14)
2022/07/04 06:40:16 [error] [exception.CHttpException.404] CHttpException: Page not found in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php:18
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php(29): HomeController->checkDomain()
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\actions\CInlineAction.php(49): HomeController->actionIndex()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): CController->run('')
#6 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('home')
#7 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#8 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(14): CApplication->run()
#9 {main}
REQUEST_URI=/home
---
2022/07/04 06:52:51 [error] [php] Trying to get property 'id' of non-object (E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\components\Controller.php:44)
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php(9): HomeController->checkDomain()
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(359): HomeController->__construct()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(276): CWebApplication->createController()
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(14): CWebApplication->run()
REQUEST_URI=/home
in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\components\Controller.php (44)
in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php (9)
in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php (14)
2022/07/04 06:53:14 [error] [php] Trying to get property 'id' of non-object (E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php:9)
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(359): HomeController->__construct()
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(276): CWebApplication->createController()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController()
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(14): CWebApplication->run()
REQUEST_URI=/home
in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php (9)
in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php (14)
2022/07/04 06:53:14 [error] [php] Trying to get property 'id' of non-object (E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php:9)
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(359): HomeController->__construct()
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(276): CWebApplication->createController()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController()
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(14): CWebApplication->run()
REQUEST_URI=/home
in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php (9)
in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php (14)
2022/07/04 06:53:14 [error] [php] Trying to get property 'id' of non-object (E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php:9)
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(359): HomeController->__construct()
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(276): CWebApplication->createController()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController()
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(14): CWebApplication->run()
REQUEST_URI=/home
in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php (9)
in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php (14)
2022/07/04 06:53:21 [error] [php] Trying to get property 'id' of non-object (E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\components\Controller.php:44)
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php(10): HomeController->checkDomain()
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(359): HomeController->__construct()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(276): CWebApplication->createController()
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(14): CWebApplication->run()
REQUEST_URI=/home
in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\components\Controller.php (44)
in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php (10)
in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php (14)
2022/07/04 06:57:42 [error] [exception.ParseError] ParseError: syntax error, unexpected ';' in E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\protected\controllers\HomeController.php:13
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(276): CWebApplication->createController('')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('home')
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(14): CApplication->run()
#4 {main}
REQUEST_URI=/home
---
2022/07/04 06:57:46 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "yii-event.com". in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('yii-event.com')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-event.com
HTTP_REFERER=http://yii-home.com/home
---
2022/07/04 06:57:56 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "yii-home.com". in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('yii-home.com')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-home.com
HTTP_REFERER=http://yii-home.com/home
---
2022/07/04 06:58:05 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "yii-home.com". in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('yii-home.com')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-home.com
HTTP_REFERER=http://yii-home.com/home
---
2022/07/04 06:58:33 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "yii-home.com". in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('yii-home.com')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-home.com
HTTP_REFERER=http://yii-home.com/home
---
2022/07/04 07:01:23 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "yii-event.com". in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('yii-event.com')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-event.com
HTTP_REFERER=http://yii-home.com/
---
2022/07/04 07:01:27 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "favicon.ico". in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://yii-home.com/
---
2022/07/04 07:01:28 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "favicon.ico". in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://yii-home.com/
---
2022/07/04 07:01:30 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "event". in E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php:486
Stack trace:
#0 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CController.php(270): CController->missingAction('event')
#1 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(282): CController->run('event')
#2 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('home/event')
#3 E:\xampp\htdocs\Yii_framwork\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 E:\xampp\htdocs\Yii_framwork\yii-1.1\yii_app\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/home/event/
---
